services: 
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${PATH_TO_APPDATA}/jellyfin/config:/config
      - ${PATH_TO_DATA}/media/tv:/data/tvshows
      - ${PATH_TO_DATA}/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    networks: 
      - mediarr 
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 5055:5055
    volumes:
      - ${PATH_TO_APPDATA}/jellyseerr/config:/app/config
    restart: unless-stopped
    networks: 
      - mediarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${PATH_TO_APPDATA}/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks: 
      - mediarr 
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${PATH_TO_APPDATA}/sonarr/config:/config
      - ${PATH_TO_DATA}/media/tv:/tv
      - ${PATH_TO_DATA}/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks: 
      - mediarr 
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${PATH_TO_APPDATA}/radarr/config:/config
      - ${PATH_TO_DATA}/media/movies:/movies
      - ${PATH_TO_DATA}/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks: 
      - mediarr 
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${PATH_TO_APPDATA}/bazarr/config:/config
      - ${PATH_TO_DATA}/media/movies:/movies
      - ${PATH_TO_DATA}/media/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    networks: 
      - mediarr 
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${PATH_TO_APPDATA}/qbittorrent/config:/config
      - ${PATH_TO_DATA}/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks: 
      - mediarr 
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${PATH_TO_APPDATA}/recyclarr/config:/config
    restart: unless-stopped
    networks: 
      - mediarr 
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8191:8191
    restart: unless-stopped
    networks: 
      - mediarr 
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 3000:3000
    volumes:
      - ${PATH_TO_APPDATA}/homepage/config:/app/config
      #- /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
    networks:
      - mediarr
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8087:8080
    volumes:
      - /:/data
      - ${PATH_TO_APPDATA}/filebrowser/config:/config
    restart: unless-stopped
    networks:
      - mediarr
networks: 
  mediarr: 
    driver: bridge
    